"""Core domain models shared across all modules."""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field


# ── Identifiers ──────────────────────────────────────────────────────

def new_id() -> str:
    return uuid.uuid4().hex


# ── Run state ────────────────────────────────────────────────────────

class RunStatus(str, Enum):
    PENDING = "pending"
    PLANNING = "planning"
    EXECUTING = "executing"
    VALIDATING = "validating"
    COMPLETED = "completed"
    FAILED = "failed"


class Run(BaseModel):
    """A single research execution from query to structured output."""

    id: str = Field(default_factory=new_id)
    query: str
    status: RunStatus = RunStatus.PENDING
    plan: Optional[ExecutionPlan] = None
    steps: list[StepResult] = Field(default_factory=list)
    claims: list[Claim] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    completed_at: Optional[datetime] = None
    metadata: dict[str, Any] = Field(default_factory=dict)

    @property
    def elapsed_seconds(self) -> float | None:
        if self.completed_at is None:
            return None
        return (self.completed_at - self.created_at).total_seconds()


# ── Planning ─────────────────────────────────────────────────────────

class PlanStep(BaseModel):
    """A single step in an execution plan."""

    id: str = Field(default_factory=new_id)
    description: str
    tool_name: str
    tool_input: dict[str, Any] = Field(default_factory=dict)
    depends_on: list[str] = Field(default_factory=list)


class ExecutionPlan(BaseModel):
    """Structured plan generated by the planner LLM."""

    steps: list[PlanStep]
    reasoning: str = ""


# ── Tool execution ───────────────────────────────────────────────────

class StepStatus(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    SUCCESS = "success"
    FAILED = "failed"
    SKIPPED = "skipped"


class StepResult(BaseModel):
    """Result of executing a single plan step."""

    step_id: str
    tool_name: str
    status: StepStatus = StepStatus.PENDING
    output: Any = None
    error: Optional[str] = None
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    retries: int = 0


# ── Claims & citations ──────────────────────────────────────────────

class EvidenceSpan(BaseModel):
    """A precise text snippet that supports or contradicts a claim."""

    source_id: str
    text: str
    start_offset: Optional[int] = None
    end_offset: Optional[int] = None


class Citation(BaseModel):
    """A reference to a source document."""

    source_id: str
    title: str
    authors: list[str] = Field(default_factory=list)
    url: Optional[str] = None
    doi: Optional[str] = None
    published_date: Optional[str] = None


class ClaimConfidence(str, Enum):
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    CONFLICTING = "conflicting"


class Claim(BaseModel):
    """An atomic verifiable statement backed by evidence."""

    id: str = Field(default_factory=new_id)
    statement: str
    confidence: ClaimConfidence = ClaimConfidence.MEDIUM
    citations: list[Citation] = Field(default_factory=list)
    evidence_spans: list[EvidenceSpan] = Field(default_factory=list)
    conflicting_evidence: list[EvidenceSpan] = Field(default_factory=list)


# ── Source documents ─────────────────────────────────────────────────

class SourceType(str, Enum):
    PAPER = "paper"
    WEBPAGE = "webpage"
    DATASET = "dataset"
    DOCUMENT = "document"


class Source(BaseModel):
    """A document retrieved and stored by the retrieval system."""

    id: str = Field(default_factory=new_id)
    source_type: SourceType
    title: str
    content: str = ""
    content_hash: Optional[str] = None
    url: Optional[str] = None
    doi: Optional[str] = None
    metadata: dict[str, Any] = Field(default_factory=dict)
    retrieved_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
